/* CFP Study — data.js */
window.DATA = {
  exam: { label: 'November 2026', date: '2026-11-15' },

  checklist: [
    {
      id: 'cl-gfp', title: 'General Financial Planning',
      items: [
        { id: 'gfp01', label: 'CFP Board financial planning process — 6 steps and what happens in each', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Process questions are frequent; know the step names and sequence cold', done: false },
        { id: 'gfp02', label: 'Three phases of client financial life cycle', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp03', label: 'CFP marks — proper use and requirements', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp04', label: 'Fiduciary duty — definition and client-planner implications', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp05', label: 'CFP Board Code of Ethics — 6 principles and how to apply them', type: 'references', priority: 'high', bucket: 'Reference', note: 'Scenario-based: given a situation, identify which principle is violated', done: false },
        { id: 'gfp06', label: 'Standards of Conduct — financial planning vs. non-planning engagements', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'gfp07', label: 'CFP Board Fitness Standards — disciplinary and appeals process', type: 'flashcards', priority: 'low', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp08', label: 'Cognitive and emotional biases — names, definitions, and how they affect decisions', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Know at least 10-12 biases; exam tests both identification and application', done: false },
        { id: 'gfp09', label: 'Client psychology — risk tolerance, loss aversion, risk capacity', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'gfp10', label: 'Communication and counseling techniques in financial planning', type: 'flashcards', priority: 'low', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp11', label: 'Statement of financial position — construction and ratio analysis', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'gfp12', label: 'Cash flow statement — construction and analysis', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'gfp13', label: 'Emergency fund strategies and savings incorporation', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp14', label: 'Debt management strategies — prioritization, credit score impact', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'gfp15', label: 'Buy vs. lease decision factors', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'gfp16', label: 'Home financing strategies', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'gfp17', label: 'TVM: FV, PV, PMT, N, I/YR calculations', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Foundation for retirement, education, and debt problems — must be automatic', done: false },
        { id: 'gfp18', label: 'TVM: inflation-adjusted (serial) payment calculation', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Serial payment = PMT growing with inflation; distinct from level payment', done: false },
        { id: 'gfp19', label: 'TVM: loan amortization and payment breakdown', type: 'calculations', priority: 'high', bucket: 'Calculation', note: '', done: false },
        { id: 'gfp20', label: 'TVM: IRR and NPV of uneven cash flows', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: '', done: false },
        { id: 'gfp21', label: 'Education funding: lump sum, level payment, and serial payment calculations', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Three-step problem: inflate tuition cost, find PV at college start, fund that PV', done: false },
        { id: 'gfp22', label: 'Education funding vehicles — 529, Coverdell, UGMA/UTMA, EE bonds; features and comparison', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp23', label: 'Education tax credits — American Opportunity, Lifetime Learning; coordination of benefit rules', type: 'references', priority: 'high', bucket: 'Reference', note: 'Cannot double-dip credits and deductions; know the phase-out ranges', done: false },
        { id: 'gfp24', label: 'Student Aid Index (SAI) — how parent vs. child assets are treated', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp25', label: 'EE/HH/I Bond — characteristics, differences, education exclusion rules', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'I bond inflation adjustment and EE bond education exclusion income limits are tested', done: false },
        { id: 'gfp26', label: 'Supply and demand, monetary/fiscal policy, business cycle phases', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp27', label: 'Inflation, deflation, disinflation, stagflation — definitions and distinctions', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp28', label: 'Bankruptcy types — Ch. 7, 11, 13; Bankruptcy Act of 2005', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp29', label: 'Consumer credit protection legislation', type: 'flashcards', priority: 'low', bucket: 'Flashcard', note: '', done: false },
        { id: 'gfp30', label: 'FDIC insurance — limits and covered accounts', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
      ]
    },
    {
      id: 'cl-rmi', title: 'Risk Management & Insurance',
      items: [
        { id: 'rmi01', label: 'Risk management process — steps and risk responses (retain, reduce, transfer, avoid)', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi02', label: 'Insurance contract terms — insurable interest, subrogation, indemnity, coinsurance', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi03', label: 'Legal concepts — negligence, liability, proximate cause', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi04', label: 'Homeowners policy forms — HO-2, HO-3, HO-4, HO-5, HO-6, HO-8; what each covers', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Know which form applies to renters, condo owners, older homes', done: false },
        { id: 'rmi05', label: 'HO coinsurance formula — calculation of reimbursement when underinsured', type: 'calculations', priority: 'high', bucket: 'Calculation', note: '(Coverage carried / Coverage required) x Loss. Required = 80% of replacement cost', done: false },
        { id: 'rmi06', label: 'Personal auto policy — coverage parts: liability, medical, uninsured motorist, physical damage', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi07', label: 'Life insurance types — term, whole, universal, variable, adjustable, joint life; features and tradeoffs', type: 'references', priority: 'high', bucket: 'Reference', note: 'Comparison questions: which type fits this client situation?', done: false },
        { id: 'rmi08', label: 'Life insurance taxation — inside buildup, MEC rules, 7-pay test, death benefit exclusion', type: 'references', priority: 'high', bucket: 'Reference', note: 'MEC triggers and tax consequences are a frequent trap', done: false },
        { id: 'rmi09', label: 'Transfer-for-value rule — what it is and all exceptions', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Exceptions: insured, partner, partnership, corporation — memorize the list', done: false },
        { id: 'rmi10', label: 'Life insurance needs analysis — human life value and needs approach calculations', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: '', done: false },
        { id: 'rmi11', label: 'Life insurance policy provisions — grace period, incontestability, suicide clause, reinstatement', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi12', label: 'Life insurance dividend options — paid-up additions, reduce premium, accumulate, cash', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi13', label: 'Life insurance riders — waiver of premium, guaranteed insurability, accelerated death benefit', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi14', label: 'Annuity types — fixed, variable, indexed; accumulation vs. distribution phase', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi15', label: 'Annuity taxation — exclusion ratio calculation, LIFO for non-qualified, 1035 exchanges', type: 'calculations', priority: 'high', bucket: 'Combo', note: 'Exclusion ratio = investment in contract / expected return', done: false },
        { id: 'rmi16', label: 'COBRA — qualifying events, coverage periods (18/29/36 months), premium rules', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Know which event = which duration; 18 months most common, 36 months for divorce/death', done: false },
        { id: 'rmi17', label: 'Individual health insurance — HMO, PPO, HDHP types; ACA rules', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi18', label: 'HSA — eligibility, contribution limits, triple tax benefit, qualified expenses', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Must be paired with HDHP; contributions, growth, and qualified withdrawals all tax-free', done: false },
        { id: 'rmi19', label: 'Medicare Parts A, B, C, D — what each covers, premiums, eligibility', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Part A = hospital (free if 40 quarters), Part B = medical, C = Advantage, D = drug', done: false },
        { id: 'rmi20', label: 'Medicare supplement (Medigap) plans — purpose and key plan differences', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi21', label: 'Medicaid and CHIP — eligibility, role in long-term care planning', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi22', label: 'Health care cost calculation — deductible, coinsurance, copay, out-of-pocket max', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: '', done: false },
        { id: 'rmi23', label: 'Disability insurance — own-occ vs. any-occ, elimination period, benefit period, riders', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'rmi24', label: 'Long-term care insurance — benefit triggers, elimination period, inflation protection', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'rmi25', label: 'Group life insurance — types, $50k exclusion rule (Sec. 79), imputed income', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Employer-paid coverage above $50k creates imputed income taxed to employee', done: false },
        { id: 'rmi26', label: 'Group health insurance — funding methods, fully insured vs. self-insured, ERISA preemption', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'rmi27', label: 'Group disability — taxation based on who pays premium', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Employer-paid premium = taxable benefit; employee-paid = tax-free benefit', done: false },
        { id: 'rmi28', label: 'Business insurance needs — key person, buy-sell agreements, BOLI', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'rmi29', label: 'Buy-sell agreement funding — cross-purchase vs. entity purchase; tax implications', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'rmi30', label: 'Workers compensation and unemployment insurance — basic rules', type: 'flashcards', priority: 'low', bucket: 'Flashcard', note: '', done: false },
      ]
    },
    {
      id: 'cl-inv', title: 'Investment Planning',
      items: [
        { id: 'inv01', label: 'Financial intermediaries, primary vs. secondary markets, market mechanisms', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv02', label: 'Money market instruments — T-bills, commercial paper, CDs; characteristics and taxation', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv03', label: 'Wash sale rule — triggering events, disallowed loss, adjusted basis', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv04', label: 'Bond terminology — par, coupon, YTM, YTC, duration, convexity, credit rating', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv05', label: 'Bond price/yield relationship and duration as sensitivity measure', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'inv06', label: 'Duration and convexity — estimated price change from rate move', type: 'calculations', priority: 'high', bucket: 'Calculation', note: '% price change = -Duration x (change in YTM / 1+YTM)', done: false },
        { id: 'inv07', label: 'Yield calculations — current yield, YTM, YTC, taxable equivalent yield', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'TEY = muni yield / (1 - marginal tax rate)', done: false },
        { id: 'inv08', label: 'Bond strategies — immunization, laddering, barbell, bullet; when to use each', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'inv09', label: 'Yield curve shapes — normal, inverted, flat; what each signals', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv10', label: 'Convertible securities — conversion value, investment value, conversion premium', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: '', done: false },
        { id: 'inv11', label: 'Preferred stock — characteristics, cumulative vs. non-cumulative, taxation', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv12', label: 'Common stock — types, voting rights, cash vs. stock dividends, splits', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv13', label: 'Mutual funds — open vs. closed end, NAV calculation, load types, share classes', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv14', label: 'ETFs, hedge funds, GICs — characteristics and use cases', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv15', label: 'Mutual fund average cost basis calculation', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: '', done: false },
        { id: 'inv16', label: 'Fundamental vs. technical analysis — key concepts and indicators', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv17', label: 'Stock valuation — DDM, P/E, price-to-book; intrinsic value calculation', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'DDM: P = D1 / (r - g); know zero growth, constant growth, multi-stage variants', done: false },
        { id: 'inv18', label: 'Options — calls vs. puts, intrinsic value, time premium, option premium formula', type: 'calculations', priority: 'high', bucket: 'Combo', note: 'Intrinsic value of call = max(S-K, 0); put = max(K-S, 0). Premium = intrinsic + time value', done: false },
        { id: 'inv19', label: 'Options strategies — covered call, protective put, straddle; hedging applications', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'inv20', label: 'Margin — initial vs. maintenance, margin call trigger price, cash to add', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Margin call price = purchase price x (1-initial margin) / (1-maintenance margin)', done: false },
        { id: 'inv21', label: 'Futures — terminology, uses, taxation (60/40 rule)', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv22', label: 'Real estate investment — forms of ownership, valuation, passive activity rules', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'inv23', label: 'Foreign securities — currency risk, exchange rate effect on returns', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: '', done: false },
        { id: 'inv24', label: 'Risk types — systematic vs. unsystematic; beta as systematic risk measure', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv25', label: 'Beta and weighted beta calculation', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Weighted beta = sum of (weight x individual beta) across portfolio', done: false },
        { id: 'inv26', label: 'Standard deviation of a single asset — calculation and 1/2/3 SD ranges', type: 'calculations', priority: 'high', bucket: 'Calculation', note: '', done: false },
        { id: 'inv27', label: 'Coefficient of variation — calculation and application', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'CV = SD / mean return; lower CV = better risk/return tradeoff', done: false },
        { id: 'inv28', label: 'Covariance and correlation coefficient — portfolio SD implication', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Perfect positive correlation (r=1) = no diversification benefit', done: false },
        { id: 'inv29', label: 'Coefficient of determination (R-squared) — interpretation', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: 'R-squared = % of portfolio variance explained by the benchmark', done: false },
        { id: 'inv30', label: 'Investment return measures — HPR, arithmetic vs. geometric mean, TWRR, MWRR', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'TWRR removes cash flow distortion; MWRR = IRR, reflects timing of flows', done: false },
        { id: 'inv31', label: 'Risk-adjusted performance — Sharpe, Treynor, Jensen\'s alpha, information ratio', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Sharpe uses SD; Treynor uses beta; Jensen\'s alpha = actual minus CAPM expected return', done: false },
        { id: 'inv32', label: 'CAPM — formula, SML, expected return calculation', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'E(R) = Rf + beta(Rm - Rf); SML plots expected return vs. beta', done: false },
        { id: 'inv33', label: 'Modern portfolio theory — efficient frontier, indifference curves, optimal portfolio', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'inv34', label: 'Efficient market hypothesis — weak, semi-strong, strong forms', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv35', label: 'Asset allocation methodologies — strategic, tactical, dynamic, core-satellite', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'inv36', label: 'Investment policy statement (IPS) — required components', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'inv37', label: 'Exam formula sheet — know what each formula is for, not just the math', type: 'references', priority: 'high', bucket: 'Reference', note: 'The exam provides a formula sheet; identifying the right formula is the skill', done: false },
      ]
    },
    {
      id: 'cl-tax', title: 'Tax Planning',
      items: [
        { id: 'tax01', label: 'Tax calculation sequence — gross income to AGI to taxable income to tax to credits', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Know the exact order; many questions test whether an item is above or below the line', done: false },
        { id: 'tax02', label: 'Items included in gross income vs. excluded — comprehensive list', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Exclusions: gifts, inheritances, life insurance proceeds, muni bond interest, workers comp', done: false },
        { id: 'tax03', label: 'Above-the-line deductions (for AGI) — complete list', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'IRA, student loan interest, alimony pre-2019, SE tax, HSA, educator expenses, etc.', done: false },
        { id: 'tax04', label: 'Below-the-line deductions — standard vs. itemized; SALT cap, mortgage interest, charitable', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'SALT = $10k cap; mortgage interest on up to $750k acquisition debt', done: false },
        { id: 'tax05', label: 'Miscellaneous itemized deductions — which remain post-TCJA', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: 'Most misc. itemized deductions were eliminated by TCJA; very few remain', done: false },
        { id: 'tax06', label: 'Marginal vs. average tax rate — distinction and application', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'tax07', label: 'Tax credits — Child Tax Credit, Child/Dependent Care, Earned Income, education credits', type: 'references', priority: 'high', bucket: 'Reference', note: 'Know income phase-outs and whether refundable or non-refundable', done: false },
        { id: 'tax08', label: 'Kiddie tax — who it applies to, how unearned income is taxed', type: 'references', priority: 'high', bucket: 'Reference', note: 'Applies to children under 19 (or 24 if student); unearned income taxed at parent\'s rate', done: false },
        { id: 'tax09', label: 'AMT — add-back items, exemption, calculation', type: 'calculations', priority: 'high', bucket: 'Combo', note: 'ISO exercise is the classic AMT trigger; also MACRS accelerated depreciation, SALT', done: false },
        { id: 'tax10', label: 'Charitable contribution deduction — AGI ceiling chart by asset and organization type', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Cash to public charity = 60%; appreciated property to public = 30%; private foundation = 20%/30%', done: false },
        { id: 'tax11', label: 'Imputed interest rules — AFR, below-market loans, gift vs. demand loans', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'tax12', label: 'Definition of dependent — qualifying child vs. qualifying relative tests', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Five tests for qualifying child: relationship, age, residency, support, joint return', done: false },
        { id: 'tax13', label: 'Capital asset vs. ordinary asset vs. Sec. 1231 asset — definitions', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Capital = everything except inventory, receivables, depreciables in business, creative works', done: false },
        { id: 'tax14', label: 'Capital gain netting process — ST vs. LT, netting order, $3k loss limit', type: 'references', priority: 'high', bucket: 'Reference', note: 'Net STCG/STCL first, then LTCG/LTCL, then net against each other', done: false },
        { id: 'tax15', label: 'Sec. 1231/1245/1250 — asset definitions, depreciation recapture tax treatment', type: 'calculations', priority: 'high', bucket: 'Combo', note: '1245 recapture = ordinary income; 1250 unrecaptured = 25% rate; net 1231 gain = LTCG', done: false },
        { id: 'tax16', label: 'Holding periods — regular purchase, inherited (always LT), gifted, like-kind exchange', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Inherited property is always long-term regardless of how long the estate held it', done: false },
        { id: 'tax17', label: 'Like-kind exchange — realized gain, recognized gain, deferred gain, basis in new property', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Boot received triggers gain recognition up to amount of gain realized', done: false },
        { id: 'tax18', label: 'Installment sale — gross profit ratio, taxable portion of each payment', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'GP% = gross profit / contract price; taxable = GP% x principal received', done: false },
        { id: 'tax19', label: 'Sec. 121 primary residence exclusion — $250k/$500k, ownership and use tests', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'tax20', label: 'Casualty and theft loss — Sec. 1033 involuntary conversion rules', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: '', done: false },
        { id: 'tax21', label: 'Rental property — rental use vs. personal use vs. mixed use; 14-day/10% rule', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'tax22', label: 'Passive activity loss rules — material participation, $25k rental exception, phase-out', type: 'references', priority: 'high', bucket: 'Reference', note: '$25k allowance phases out between $100k-$150k AGI', done: false },
        { id: 'tax23', label: 'At-risk rules — what counts as at-risk basis', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'tax24', label: 'Direct participation programs — tax benefits, public vs. private LPs', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'tax25', label: 'MACRS depreciation — recovery periods, calculation, Sec. 179 election', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Sec. 179 immediate expensing; MACRS half-year convention in year of acquisition', done: false },
        { id: 'tax26', label: 'Sec. 1202 and 1244 stock — gain exclusion and ordinary loss treatment', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '1202: up to 100% gain exclusion on QSBS held 5+ years; 1244: up to $50k/$100k ordinary loss', done: false },
        { id: 'tax27', label: 'C corporation — characteristics, accumulated earnings tax, PHC tax', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'tax28', label: 'Pass-through entities — S corp, partnership, LLC; key tax attributes', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'tax29', label: 'Self-employment tax — calculation, deductibility', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'SE tax = 15.3% on 92.35% of net SE income; 50% deductible above the line', done: false },
        { id: 'tax30', label: 'Home office deduction — regular and exclusive use, two calculation methods', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'tax31', label: 'Hobby loss rules — presumption of profit, income inclusion', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'tax32', label: 'Investment interest expense deduction — limit and carryover', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: 'Limited to net investment income; excess carries forward indefinitely', done: false },
        { id: 'tax33', label: 'NII surtax (3.8%) and additional Medicare tax (0.9%) — thresholds and applicable income', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '3.8% on lesser of NII or MAGI above threshold; 0.9% on earned income above threshold', done: false },
        { id: 'tax34', label: 'Dividend taxation — qualified vs. non-qualified; rates', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Qualified dividends taxed at LTCG rates; non-qualified at ordinary rates', done: false },
        { id: 'tax35', label: 'Annuity taxation — exclusion ratio, accumulation phase, surrender charges', type: 'calculations', priority: 'high', bucket: 'Combo', note: '', done: false },
        { id: 'tax36', label: 'Life insurance cash value taxation — inside buildup, loans, surrenders, 1035 exchange', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'tax37', label: 'Tax implications of divorce — alimony pre vs. post TCJA, child support, property transfers', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Post-2018 alimony: no deduction to payer, no income to recipient', done: false },
        { id: 'tax38', label: 'Estate/trust income taxation — DNI, grantor trust rules, flow-through to beneficiaries', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'tax39', label: 'Tax authority hierarchy — primary vs. secondary sources, audit types, penalties', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
      ]
    },
    {
      id: 'cl-ret', title: 'Retirement Planning',
      items: [
        { id: 'ret01', label: 'Retirement funding calculation — two-step TVM: accumulation and distribution phases', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Step 1: find lump sum needed at retirement. Step 2: find PMT to fund that lump sum', done: false },
        { id: 'ret02', label: 'Qualified plan requirements — coverage tests, contribution limits, nondiscrimination', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'ret03', label: 'Top-heavy plan — definition, 60% key employee test, minimum contribution requirements', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret04', label: 'Highly compensated employee definition', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '$155k+ (indexed) or top 20% of employees by compensation', done: false },
        { id: 'ret05', label: 'Key employee definition', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Officer $220k+; 5% owner; 1% owner with comp over $150k', done: false },
        { id: 'ret06', label: 'Defined benefit plan — benefit formula, funding, advantages for older high-earners', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'ret07', label: 'Cash balance plan — features, portable account balance, hybrid characteristics', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret08', label: 'Money purchase pension plan — mandatory contribution, characteristics', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret09', label: 'Profit sharing plan — discretionary contribution, allocation formulas', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret10', label: 'Age-based profit sharing and new comparability plans', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: 'Favor older/higher-paid employees; tested with integration questions', done: false },
        { id: 'ret11', label: 'ESOP — characteristics, NUA benefit, S corp ESOP rules', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret12', label: '401(k) — elective deferral limit, employer match, catch-up contribution', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret13', label: 'ADP/ACP testing — calculation, safe harbor methods, correction methods', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'HCE average cannot exceed NHCE average by more than 2% or 2x NHCE rate', done: false },
        { id: 'ret14', label: 'SIMPLE 401(k) — features, limits, eligibility vs. traditional 401(k)', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret15', label: 'Roth 401(k) — contribution limits, no income limit, distribution rules', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret16', label: 'Solo 401(k) — who qualifies, employee plus employer contribution calculation', type: 'calculations', priority: 'medium', bucket: 'Calculation', note: '', done: false },
        { id: 'ret17', label: 'SIMPLE IRA — employer size limit, contribution limits, 2-year rule, early withdrawal penalty', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '2-year rule: early withdrawal within first 2 years = 25% penalty (not 10%)', done: false },
        { id: 'ret18', label: 'SEP IRA — eligibility, contribution limit (25%/66k), employee eligibility rules', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret19', label: 'SEP vs. SIMPLE — side-by-side comparison of all key features', type: 'references', priority: 'high', bucket: 'Reference', note: 'This comparison is heavily tested; build it as a table', done: false },
        { id: 'ret20', label: '403(b) — eligibility, contribution limits, 15-year catch-up, similarities to 401(k)', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret21', label: '457 plans — governmental vs. non-governmental, distribution rules, no 10% penalty', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Governmental 457 can roll to IRA; non-governmental cannot', done: false },
        { id: 'ret22', label: 'Multiple plan coordination — maximum elective deferral across multiple plans', type: 'calculations', priority: 'high', bucket: 'Calculation', note: '$23k (2024) elective deferral limit is per individual, not per plan', done: false },
        { id: 'ret23', label: 'Traditional IRA — contribution limits, deductibility phase-out, active participant rules', type: 'calculations', priority: 'high', bucket: 'Combo', note: 'Deductibility depends on filing status, MAGI, and whether covered by plan at work', done: false },
        { id: 'ret24', label: 'Traditional IRA deductibility calculation — phaseout range application', type: 'calculations', priority: 'high', bucket: 'Calculation', note: '', done: false },
        { id: 'ret25', label: 'Roth IRA — income limits, contribution phase-out, no RMDs, 5-year rule', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret26', label: 'Roth IRA distribution ordering rules — contributions first, then conversions, then earnings', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'ret27', label: 'Roth IRA conversions — tax treatment, 5-year clock, backdoor Roth strategy', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'ret28', label: 'Roth 401(k) vs. Roth IRA vs. traditional 401(k) — comparison', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'ret29', label: 'Rollover vs. direct transfer — 60-day window, 20% withholding, 1-rollover-per-year rule', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '60-day rollover: 20% withholding applies to qualified plan distributions', done: false },
        { id: 'ret30', label: 'Inherited and stretch IRA — 10-year rule post-SECURE, eligible designated beneficiaries', type: 'references', priority: 'high', bucket: 'Reference', note: 'SECURE Act 2.0 changes are heavily tested; know who qualifies as EDB', done: false },
        { id: 'ret31', label: 'RMDs — required beginning date, calculation using Uniform Lifetime Table', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'RMD = prior year-end balance / life expectancy factor; RBD = April 1 after age 73', done: false },
        { id: 'ret32', label: 'RMD rules when owner dies before vs. after RBD — distribution options', type: 'references', priority: 'high', bucket: 'Reference', note: 'Before RBD: 5-year rule or life expectancy. After RBD: at least as rapidly as before', done: false },
        { id: 'ret33', label: 'Early distribution penalty (10%) — exceptions for qualified plans vs. IRA', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '72(t) SEPP exception; IRA-only: first home, education, health insurance premiums', done: false },
        { id: 'ret34', label: 'Qualified plan loans — $50k/50% limit, repayment, deemed distribution rules', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Loans from non-governmental 457 plans are not permitted', done: false },
        { id: 'ret35', label: 'NUA — tax treatment, when advantageous, lump sum distribution requirement', type: 'calculations', priority: 'high', bucket: 'Combo', note: 'NUA taxed at LTCG rates; only cost basis is ordinary income at distribution', done: false },
        { id: 'ret36', label: 'Vesting schedules — cliff vs. graded for DC, DB, and top-heavy plans', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Top-heavy: 2-year cliff or 6-year graded for non-key employees', done: false },
        { id: 'ret37', label: 'QJSA and QPSA — automatic survivor benefits, waiver requirements', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret38', label: 'QDROs — what qualifies, how benefits are divided, taxation to alternate payee', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret39', label: 'Social Security eligibility — 40 credits, benefit calculation (AIME, PIA)', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret40', label: 'Social Security retirement — full retirement age, early reduction, delayed credits', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Early: reduced 5/9 of 1% per month for first 36 months, 5/12 beyond; delayed = 8%/yr', done: false },
        { id: 'ret41', label: 'Social Security disability and survivor benefits — eligibility and calculation', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret42', label: 'Social Security benefit reduction for earned income — thresholds and reduction formula', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Below FRA: $1 reduction per $2 over $22,320 (2024); year of FRA: $1 per $3 over higher limit', done: false },
        { id: 'ret43', label: 'Taxation of Social Security — provisional income formula, 50%/85% inclusion thresholds', type: 'calculations', priority: 'high', bucket: 'Combo', note: 'Provisional income = AGI + tax-exempt interest + 50% of SS benefit', done: false },
        { id: 'ret44', label: 'Social Security integration with DC plans — excess and offset methods', type: 'references', priority: 'medium', bucket: 'Reference', note: 'Plans that cannot integrate: 401(k) elective deferrals, SIMPLE, SEP, 403(b), 457', done: false },
        { id: 'ret45', label: 'Retirement plan selection — matching employer and employee characteristics to plan type', type: 'references', priority: 'high', bucket: 'Reference', note: 'Core scenario question; know which plan fits which employer situation', done: false },
        { id: 'ret46', label: 'Nonqualified deferred compensation — NQDC, Sec. 409A, constructive receipt, SRF', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'ret47', label: 'NQDC funding methods — rabbi trust, secular trust, COLI', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'ret48', label: 'ISO vs. NQSO vs. ESPP — tax treatment at grant, exercise, and sale', type: 'calculations', priority: 'high', bucket: 'Combo', note: 'ISO: no ordinary income at exercise (AMT item); NQSO: spread at exercise = ordinary income', done: false },
        { id: 'ret49', label: 'Equity compensation — SARs, restricted stock, phantom stock, performance shares', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
      ]
    },
    {
      id: 'cl-est', title: 'Estate Planning',
      items: [
        { id: 'est01', label: 'Estate planning process — steps, goals, common pitfalls', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'est02', label: 'Property ownership forms — JTWROS, TIC, community property, tenancy by entirety', type: 'references', priority: 'high', bucket: 'Reference', note: 'Know nontax characteristics of each: right of survivorship, creditor protection, etc.', done: false },
        { id: 'est03', label: 'Property ownership matrix — gross estate inclusion, probate, basis after death, who inherits', type: 'references', priority: 'high', bucket: 'Reference', note: '4 ownership types x 4 questions = 16 cells; build this as a grid', done: false },
        { id: 'est04', label: 'Community property vs. separate property — determination and planning implications', type: 'references', priority: 'high', bucket: 'Reference', note: '9 community property states; both spouses get full step-up in community property', done: false },
        { id: 'est05', label: 'Federal gift tax — annual exclusion, present interest requirement, filing requirements', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Annual exclusion: $18k (2024); requires present interest (not future interest)', done: false },
        { id: 'est06', label: 'Gift tax calculation — total gifts to taxable gifts to tentative tax to unified credit', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Must account for prior taxable gifts; tax is cumulative over lifetime', done: false },
        { id: 'est07', label: 'Gift tax valuation — FMV, discounts (lack of marketability, minority interest), Chapter 14', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'est08', label: 'Unified credit and applicable exclusion amount — current amount and portability', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '$13.61M per person (2024); portability allows DSUE to transfer to surviving spouse', done: false },
        { id: 'est09', label: 'Gift-splitting — requirements, election, effect on estate', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'Requires Form 709 election; both spouses must consent; doubles annual exclusion', done: false },
        { id: 'est10', label: 'Inter vivos gifting strategies — GRAT, GRUT, QPRT, installment sale, SCINs, private annuity', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'est11', label: 'Business succession techniques — FLP, buy-sell, installment sale', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'est12', label: 'ILIT — crummey powers, incidents of ownership, 3-year rule', type: 'references', priority: 'high', bucket: 'Reference', note: 'Insurance in ILIT not in gross estate if no incidents of ownership and 3-year rule satisfied', done: false },
        { id: 'est13', label: 'Probate — what goes through it, advantages and disadvantages, personal representative role', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'est14', label: 'Will requirements — valid will elements, types of wills, common clauses', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'est15', label: 'Intestate succession — when it applies, distribution order', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'est16', label: 'Will substitutes — POD, TOD, joint tenancy, trusts, retirement accounts', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'est17', label: 'Gross estate inclusions — Sec. 2033-2044; revocable trusts, life insurance, annuities, QTIP', type: 'references', priority: 'high', bucket: 'Reference', note: 'Sec. 2035: 3-year rule for transferred life insurance; 2036: retained life estate', done: false },
        { id: 'est18', label: 'Gross estate to adjusted gross estate to taxable estate to tentative tax base calculation', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Deductions: marital deduction, charitable deduction, debts, admin expenses', done: false },
        { id: 'est19', label: 'Federal estate tax calculation — tentative tax, unified credit, prior gift tax paid', type: 'calculations', priority: 'high', bucket: 'Calculation', note: 'Net estate tax = tentative tax on tentative tax base minus unified credit minus prior gift taxes paid', done: false },
        { id: 'est20', label: 'Marital deduction — unlimited, terminable interest rule, exceptions (QTIP, GPOA, estate trust)', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'est21', label: 'Testamentary trusts — A/B/C trust structure; when and why used', type: 'references', priority: 'high', bucket: 'Reference', note: 'A = marital/QTIP, B = credit shelter, C = QTIP; B trust keeps assets out of surviving spouse estate', done: false },
        { id: 'est22', label: 'Trust features — CRAT, CRUT, GRAT, GRUT, QPRT; income and remainder beneficiaries, tax treatment', type: 'references', priority: 'high', bucket: 'Reference', note: 'Charitable = CRAT/CRUT; grantor retained = GRAT/GRUT/QPRT', done: false },
        { id: 'est23', label: '2503(b) vs. 2503(c) vs. Crummey trust — income distribution, minor access, taxation', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '2503(b): income must be distributed; 2503(c): accumulate until 21; Crummey: withdrawal right = present interest', done: false },
        { id: 'est24', label: 'GPOA trust — gross estate inclusion, when used', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: 'GPOA property IS included in holder gross estate; SPOA (limited POA) is not', done: false },
        { id: 'est25', label: 'Credit shelter (bypass) trust — purpose, funding, interaction with portability', type: 'references', priority: 'high', bucket: 'Reference', note: 'Keeps up to exclusion amount out of surviving spouse taxable estate', done: false },
        { id: 'est26', label: 'Sec. 2032A special use valuation — eligibility, recapture', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'est27', label: 'Sec. 303 stock redemption — eligibility (greater than 35% of adjusted gross estate), purpose', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'est28', label: 'Sec. 6166 installment payment of estate taxes — eligibility, interest, acceleration triggers', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'est29', label: 'Estate liquidity — cash requirements, premortem planning techniques', type: 'references', priority: 'medium', bucket: 'Reference', note: '', done: false },
        { id: 'est30', label: 'Postmortem planning — alternate valuation date, QTIP election, disclaimer, Sec. 303/6166', type: 'references', priority: 'high', bucket: 'Reference', note: 'Alternate valuation date = 6 months after death; must reduce both estate value AND tax', done: false },
        { id: 'est31', label: 'Generation-skipping transfer tax — skip persons, taxable termination, distribution, direct skip', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'est32', label: 'GSTT exemption and calculation', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: 'GSTT exemption = same as estate/gift tax exemption ($13.61M in 2024)', done: false },
        { id: 'est33', label: 'Income tax implications of estate transfers — carryover basis vs. step-up, IRD', type: 'references', priority: 'high', bucket: 'Reference', note: 'IRD: income decedent was entitled to but did not receive; no step-up in basis', done: false },
        { id: 'est34', label: 'Charitable giving strategy — which property to give to charity (high-gain, IRD assets)', type: 'references', priority: 'high', bucket: 'Reference', note: '', done: false },
        { id: 'est35', label: 'Incapacity planning — durable POA, healthcare proxy, living will, guardianship/conservatorship', type: 'flashcards', priority: 'high', bucket: 'Flashcard', note: '', done: false },
        { id: 'est36', label: 'Special needs planning — special needs trusts, Medicaid eligibility', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'est37', label: 'Nontraditional family planning — cohabitation, same-sex couples, domestic partners', type: 'flashcards', priority: 'medium', bucket: 'Flashcard', note: '', done: false },
        { id: 'est38', label: 'Fiduciary selection — trustee, guardian, conservator, personal representative considerations', type: 'flashcards', priority: 'low', bucket: 'Flashcard', note: '', done: false },
      ]
    },
  ],

  /* ── Flashcard decks — placeholder shells, fill in content later ── */
  decks: [
    { id: 'gfp', title: 'General Financial Planning', count: 30, cards: [] },
    { id: 'rmi', title: 'Risk Management & Insurance', count: 30, cards: [] },
    { id: 'inv', title: 'Investment Planning', count: 37, cards: [] },
    { id: 'tax', title: 'Tax Planning', count: 39, cards: [] },
    { id: 'ret', title: 'Retirement Planning', count: 49, cards: [] },
    { id: 'est', title: 'Estate Planning', count: 38, cards: [] },
  ],

  /* ── References — placeholder shells ── */
  references: [
    { id: 'sep-simple', title: 'SEP vs. SIMPLE IRA', kind: 'table', blurb: 'Side-by-side comparison of key features.', columns: ['', ''], rows: [] },
    { id: 'roth-trad', title: 'Roth vs. Traditional IRA', kind: 'table', blurb: 'Side-by-side of the two individual retirement accounts.', columns: ['', ''], rows: [] },
    { id: 'property', title: 'Property Ownership Matrix', kind: 'table', blurb: 'Gross estate, probate, basis, and inheritance by ownership type.', columns: ['', ''], rows: [] },
    { id: 'trusts', title: 'Trust Comparison', kind: 'table', blurb: 'CRAT, CRUT, GRAT, GRUT, QPRT, Credit Shelter, QTIP features.', columns: ['', ''], rows: [] },
    { id: 'roth-conv', title: 'Roth Conversion Decision Tree', kind: 'tree', blurb: 'Walk the decision to convert a Traditional IRA to Roth.', tree: null },
    { id: 'plan-select', title: 'Retirement Plan Selection', kind: 'tree', blurb: 'Which plan fits which employer situation?', tree: null },
  ],

  /* ── Calculations — placeholder shells ── */
  calcs: [
    { id: 'tvm-fv', title: 'TVM — Future Value', blurb: 'Grow a single sum forward at a fixed rate.', formula: 'FV = PV x (1 + i)^n', steps: [] },
    { id: 'tvm-serial', title: 'TVM — Serial (Inflation-Adjusted) Payment', blurb: 'PMT that grows with inflation each year.', formula: '', steps: [] },
    { id: 'edu-fund', title: 'Education Funding', blurb: 'Three-step: inflate cost, find PV at start, fund that PV.', formula: '', steps: [] },
    { id: 'ret-needs', title: 'Retirement Needs Analysis', blurb: 'Two-step TVM: accumulation then distribution.', formula: '', steps: [] },
    { id: 'like-kind', title: 'Like-Kind Exchange', blurb: 'Realized, recognized, deferred gain and new basis.', formula: '', steps: [] },
    { id: 'install-sale', title: 'Installment Sale', blurb: 'Gross profit ratio and taxable portion of each payment.', formula: '', steps: [] },
    { id: 'estate-tax', title: 'Estate Tax Calculation', blurb: 'Gross estate through net federal estate tax due.', formula: '', steps: [] },
    { id: 'rmd', title: 'Required Minimum Distribution', blurb: 'RMD using prior year-end balance and life expectancy factor.', formula: '', steps: [] },
    { id: 'ho-coins', title: 'HO Coinsurance Formula', blurb: 'Reimbursement when dwelling is underinsured.', formula: '(Carried / Required) x Loss', steps: [] },
    { id: 'margin', title: 'Margin Call', blurb: 'Trigger price and cash required to meet margin call.', formula: '', steps: [] },
  ],
};
